name: Create Release
run-name: Resume Release
on:
    workflow_run:
        workflows: ['Build']
        types: [completed]
jobs:
    release:
        name: Create Release
        runs-on: ubuntu-latest
        steps:     
            - name: generate FOO unique variable based on timestamp
              run: echo FOO=$(date +%s) >> $GITHUB_ENV
              
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Create Release
              id: create_release
              uses: svenstaro/upload-release-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: Sathya_Bhat_Resume_Latest.pdf
                asset_name: ${{ env.FOO }}_Sathya_Bhat_Resume_Latest.pdf
                tag: ${{ env.FOO }}
                overwrite: true
                body: "Sample Text"
